#!/usr/bin/env bash
set -euo pipefail

build_dir="$(pwd)/out"
lib_dir="lib"

usage()
{
    echo "
    Commands: 
        test [libdir]  - build & run gTest for specified library.
        debug [libdir] - build & debug specified library.

        [libdir]       - one of the directories in lib/
    "
}

if [ -z "${1+x}" ]; then
    usage
    exit 1
fi

if [ -z "${2+x}" ]; then
    usage
    exit 1
fi

if [ ! -d "${lib_dir}/$2" ]; then
    echo "=> ERROR: Library directory does not exist in ${lib_dir}/ <="
    usage
    exit 1
fi

make_debug()
{
    echo ">> Building $1 <<"
    cmake -G Ninja -S . -B "${build_dir}" -DMY_PROG="$1"
    cmake --build "${build_dir}" -- all
}

case "$1" in
    "test")
        make_debug $2
        echo ">> Run $2 Test <<"
        ${build_dir}/bin/test.out
        ;;
    "debug")
        make_debug $2
        ;;
    *)
        usage
        ;;
esac
