#!/usr/bin/env bash
set -euo pipefail

build_dir="${PWD}/out"
lib_dir="${PWD}/lib"

usage()
{
    echo "
Commands: 
    all           - Build all with Debug flag.
    test [libdir] - Build all & run gTest for specified library.
    clean         - Deletes build directory.

        [libdir]  - one of the directories in lib/
    "
}

if [ -z "${1+x}" ]; then
    usage
    exit 1
fi

clean()
{
    rm -rf $build_dir
}

make_all()
{
    update_vscode_configs
    echo ">> Building all with debug flags <<"
    cmake -G Ninja -S . -B "${build_dir}"
    cmake --build "${build_dir}" -- all
}

run_test()
{
    if [ -n "${1-}" ]; then
        if [ ! -d "${lib_dir}/$1" ]; then
            echo "=> ERROR: Library directory $1 does not exist in ${lib_dir}/ <="
            usage
            exit 1
        fi
        make_all
        echo ">> Run $1 Test <<"
        "${build_dir}/bin/$1"
    else
        usage
        exit 1
    fi
}

update_vscode_configs()
{
    echo ">> Synchronizing libraries in VS Code configurations <<"
    python3 -c "
import os, re
libs = sorted([f for f in os.listdir('lib') if os.path.isdir(os.path.join('lib', f))])
formatted = '[\n' + ',\n'.join(f'            \"{lib}\"' for lib in libs) + '\n          ]'
for p in ['.vscode/launch.json', '.vscode/tasks.json']:
    if os.path.exists(p):
        with open(p, 'r') as file:
            content = file.read()
        new_content = re.sub(r'\"options\":\s*\[[^\]]*\]', f'\"options\": {formatted}', content)
        with open(p, 'w') as file:
            file.write(new_content)
"
}

case "$1" in
    "all")
        make_all
        ;;
    "test")
        run_test "${2-}"
        ;;
    "clean")
        clean
        ;;
    *)
        usage
        exit 1
        ;;
esac
